version: "3.7"

services:



    postgresql-container:
        image: postgres:14
        container_name: postgresql-container
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5431:5432
        volumes:
            - postgresql_volume:/var/lib/postgresql/data
            - ./SQL:/docker-entrypoint-initdb.d/

volumes:
  postgresql_volume: