version: "3.7"

services:
    smart-api:
        container_name: smart-api
        build:
            context: .
            dockerfile: ./Dockerfile
        image: smart-api:1.0
        ports:
            - 8080:8080
        depends_on:
            postgresql-container:
                condition: service_healthy

    postgresql-container:
        image: postgres:14
        container_name: postgresql-container
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
            - postgresql_volume:/var/lib/postgresql/data
            - ./SQL:/docker-entrypoint-initdb.d/
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
volumes:
  postgresql_volume: